nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ~/new_opt/html:/usr/share/nginx/html
php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - ~/new_opt/html:/usr/share/nginx/html
mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ~/new_opt/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
redis:
    build: ./redis
    ports:
      - "6379:6379"

